
#google_analytics: UA-NNNNNNNN-N

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

title: 'Decrypting Mr. Robot'
description: "Hello Friend"

header_pages:
  - index.md
  - about.md

style: dark

footer: 'follow me on <a href="https://twitter.com/dotAadarsh">twitter</a>'

plugins:
  - jekyll-seo-tag
